siteTitle="Tuckerman Style Guide"
baseColor = "#333333"
linkPrefix = "/gatsby-starter-documentation"
docPages = [
  "/docs/",
  "/docs/brand-framework/",
  "/docs/getting-started/",
  "/docs/how-to-run/",
  "/docs/some-react-code/",
  "/docs/the-next-step/",
  "/docs/conclusion/",
  "/docs/Typography/"

]

brand-framework-links = [
"http://github.com"
]
